import { format } from "date-fns";
import { nanoid } from "nanoid";

const sessArr = [
  {
    id: 1,
    course: "APPA/RADAR OPERATION",
    code: "RADAR",
    codeAlt: "25",
    newAmount: 55000,
    renewAmount: 45000,
  },
  {
    id: 2,
    course: "MOTORMAN",
    code: "MOTM",
    codeAlt: "7",
    newAmount: 80000,
    renewAmount: 70000,
  },
  {
    id: 3,
    course: "EFFICIENT DECK HAND",
    code: "EDH",
    codeAlt: "6",
    newAmount: 120000,
    renewAmount: 100000,
  },
  {
    id: 4,
    batch: "068",
    course: "RADAR/ARPA MANAGEMENT LEVEL",
    code: "RADAR",
    codeAlt: "NIL",
    newAmount: 55000,
    renewAmount: 45000,
  },
  {
    id: 5,
    course: "INTERNATIONAL SHIP & PORT FACILITIES (ISPS) SECURITY AWARENESS",
    code: "ISPS",
    codeAlt: "11",
    newAmount: 80000,
    renewAmount: 70000,
  },
  {
    id: 6,
    course: "BASIC OIL, CHEMICAL AND LIQUEFIED GAS TANKER CARGO OPERATIONS",
    code: "OTF",
    codeAlt: "5",
    newAmount: 120000,
    renewAmount: 100000,
  },
  {
    id: 7,
    course:
      "PROFICIENCY IN SURVIVAL CRAFT & RESCUE BOATS (OTHER THAN FAST RESCUE BOATS)",
    code: "PSCR",
    codeAlt: "15",
    newAmount: 55000,
    renewAmount: 45000,
  },
  {
    id: 595,
    course: "PROFICIENCY IN SURVIVAL CRAFT, RESCUE BOATS AND FAST RESCUE BOATS",
    code: "PSCR",
    codeAlt: "31",
    newAmount: 80000,
    renewAmount: 70000,
  },
  {
    id: 8,
    course: "Advanced Fire Fighting Certificate",
    code: "ADFF",
    codeAlt: "8",
    newAmount: 120000,
    renewAmount: 100000,
  },
  {
    id: 9,
    course: "GMDSS RADIO OPERATORS",
    code: "GMDSS",
    codeAlt: "15",
    newAmount: 55000,
    renewAmount: 45000,
  },
  {
    id: 10,
    course: "STCW BASIC SAFETY TRAINING",
    code: "STCW",
    codeAlt: "1-4",
    newAmount: 80000,
    renewAmount: 70000,
  },
];

const fake = [
  {
    lid: nanoid(),
    gsm: Math.random() * 100,
    amount: 55000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "GMDSS",
    codeAlt: "1-2",
    courseName: "GMDSS",
    dob: "12-Apr-2000",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),
    fullName: "Evans Diegbe Diegbe",
    marital: "Single",
    means: "NationalId",
    meansId: "848499494",
    state: "Delta State",
    status: false,
    photo: "two.jpg",
  },
  {
    gsm: Math.random() * 100,
    lid: nanoid(),

    amount: 120000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "ISPS",
    codeAlt: "11",
    courseName: "Inpector Sergent Pascal Sequence",
    dob: "12-Apr-2000",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),

    fullName: "Wex Daniel Adenikinju",
    marital: "Married",
    means: "NationalId",
    meansId: "848499494",
    state: "Ibadan State",
    status: false,
    photo: "two.jpg",
  },
  {
    gsm: Math.random() * 100,
    lid: nanoid(),

    amount: 80000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "EDH",
    codeAlt: "8",
    courseName: "Education Disater Hiuse",
    dob: "12-Apr-2000",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),

    fullName: "Junior John Doe",
    marital: "married",
    means: "NationalId",
    meansId: "848499494",
    state: "Lagos State",
    status: false,
    photo: "two.jpg",
  },
  {
    gsm: Math.random() * 100,
    lid: nanoid(),

    amount: 45000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "STCW",
    codeAlt: "1-22",
    courseName: "STCW",
    dob: "12-Apr-2000",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),

    fullName: "Chiboy Molt Run",
    marital: "single",
    means: "NationalId",
    meansId: "848499494",
    state: " State",
    status: false,
    photo: "two.jpg",
  },
  {
    gsm: Math.random() * 100,
    lid: nanoid(),

    amount: 55000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "OTF",
    codeAlt: "55",
    courseName: "OTFFF",
    dob: "12-Apr-2000",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),

    fullName: "cha cha cha",
    marital: "single",
    means: "NationalId",
    meansId: "848499494",
    state: " State",
    status: false,
    photo: "two.jpg",
  },
  {
    gsm: Math.random() * 100,
    lid: nanoid(),

    amount: 120000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "RADAR",
    codeAlt: "jf",
    courseName: "RADAR Management",
    dob: "12-Apr-2000",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),

    fullName: "Doubra toniprr Vic",
    marital: "single",
    means: "NationalId",
    meansId: "848499494",
    state: " State",
    status: false,
    photo: "two.jpg",
  },
];

const fakeData = fake.map((ele, i) => ({
  ...ele,
  gender: `${i % 2 === 0 ? "Male" : "Female"}`,
}));

export { sessArr, fakeData };
