import { format } from "date-fns";
import { nanoid } from "nanoid";

const months = [
  { value: "", label: "All Months" },
  { value: "1", label: "January" },
  { value: "2", label: "February" },
  { value: "3", label: "March" },
  { value: "4", label: "April" },
  { value: "5", label: "May" },
  { value: "6", label: "June" },
  { value: "7", label: "July" },
  { value: "8", label: "August" },
  { value: "9", label: "September" },
  { value: "10", label: "October" },
  { value: "11", label: "November" },
  { value: "12", label: "December" },
];

const family = [
  {
    id:'ADFF',
    mainFamily:'STALKER2',
    otherFamily:'Cindybob',
    normal:'Arial'
  },
  {
    id:'EDH',
    mainFamily:'STALKER2',
    otherFamily:'Cindybob',
    normal:'Arial'
  },
  {
    id:'ISPS',
    mainFamily:'STALKER2',
    otherFamily:'Cindybob',
    normal:'Arial'
  },
  {
    id:'OTF',
    mainFamily:'STALKER2',
    otherFamily:'Cindybob',
    normal:'Arial'
  },
  {
    id:'PSCR',
    mainFamily:'STALKER2',
    otherFamily:'Cindybob',
    normal:'Arial'
  },
  {
    id:'STCW',
    mainFamily:'BRITANIC',
    otherFamily:'Cindybob',
    normal:'Arial'
  },
  {
    id:'MOTM',
    mainFamily:'BRITANIC',
    otherFamily:'Cindybob',
    normal:'Arial'
  },
  {
    id:'RADAR',
    mainFamily:'Hoefler Text',
    otherFamily:'Cindybob',
    normal:'Arial'
  },
  {
    id:'GMDSS',
    mainFamily:'Hoefler Text',
    otherFamily:'Cindybob',
    normal:'Arial'
  },
]

const fake = [
  {
    lid: nanoid(),
    amount: 55000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "STCW",
    codeAlt: "1-4",
    courseName: "STCW BASIC SAFETY TRAINING",
    dob: "2000-04-12",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),
    fullName: "Evans Diegbe Diegbe",
    marital: "Single",
    means: "NationalId",
    meansId: "848499494",
    state: "Delta State",
    status: false,
    photo: "two.jpg",
  },
  {
    lid: nanoid(),

    amount: 70000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "ISPS",
    codeAlt: "11",
    courseName:
      "INTERNATIONAL SHIP & PORT FACILITIES (ISPS) SECURITY AWARENESS",
    dob: "2000-04-12",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),
    isRenewal: true,
    fullName: "Wex Daniel Adenikinju",
    marital: "Married",
    means: "NationalId",
    meansId: "848499494",
    state: "Ibadan State",
    status: false,
    photo: "two.jpg",
  },
  {
    lid: nanoid(),

    amount: 65000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "EDH",
    codeAlt: "6",
    courseName: "EFFICIENT DECK HAND",
    dob: "2000-04-12",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),

    fullName: "Junior John Doe",
    marital: "married",
    means: "NationalId",
    meansId: "848499494",
    state: "Lagos State",
    status: false,
    photo: "two.jpg",
  },
  {
    gsm: Math.random() * 100,
    lid: nanoid(),

    amount: 140000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "PSCR",
    codeAlt: "31",
    courseName:
      "PROFICIENCY IN SURVIVAL CRAFT, RESCUE BOATS AND FAST RESCUE BOATS",
    dob: "2000-04-12",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),

    fullName: "Chiboy Molt Run",
    marital: "single",
    means: "NationalId",
    meansId: "848499494",
    state: " State",
    status: false,
    photo: "two.jpg",
  },
  {
    gsm: Math.random() * 100,
    lid: nanoid(),

    amount: 65000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "MOTM",
    codeAlt: "7",
    courseName: "MOTORMAN",
    dob: "2000-04-12",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),

    fullName: "cha cha cha",
    marital: "single",
    means: "NationalId",
    meansId: "848499494",
    state: " State",
    status: false,
    photo: "two.jpg",
  },
  {
    gsm: Math.random() * 100,
    lid: nanoid(),

    amount: 140000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "RADAR",
    codeAlt: "25",
    courseName: "APPA/RADAR OPERATION",
    dob: "2000-04-12",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),

    fullName: "Doubra toniprr Vic",
    marital: "single",
    means: "NationalId",
    meansId: "848499494",
    state: " State",
    status: false,
    photo: "two.jpg",
  },
  {
    lid: nanoid(),
    amount: 67000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "STCW",
    codeAlt: "1-4",
    courseName: "STCW BASIC SAFETY TRAINING",
    dob: "2000-04-12",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),
    fullName: "Derick James Diegbe ",
    marital: "Single",
    means: "NationalId",
    meansId: "848499494",
    state: "Delta State",
    status: false,
    photo: "two.jpg",
  },
  {
    lid: nanoid(),

    amount: 80000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "ISPS",
    codeAlt: "11",
    courseName:
      "INTERNATIONAL SHIP & PORT FACILITIES (ISPS) SECURITY AWARENESS",
    dob: "2000-04-12",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),
    isRenewal: true,
    fullName: "John Godwin Wanipere",
    marital: "Married",
    means: "NationalId",
    meansId: "848499494",
    state: "Ibadan State",
    status: false,
    photo: "two.jpg",
  },
  {
    lid: nanoid(),

    amount: 100000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "EDH",
    codeAlt: "6",
    courseName: "EFFICIENT DECK HAND",
    dob: "2000-04-12",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),

    fullName: "Michael Tokoni Victor",
    marital: "married",
    means: "NationalId",
    meansId: "848499494",
    state: "Lagos State",
    status: false,
    photo: "two.jpg",
  },
  {
    gsm: Math.random() * 100,
    lid: nanoid(),

    amount: 970000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "PSCR",
    codeAlt: "31",
    courseName:
      "PROFICIENCY IN SURVIVAL CRAFT, RESCUE BOATS AND FAST RESCUE BOATS",
    dob: "2000-04-12",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),

    fullName: "Owei Samuelson Favour",
    marital: "single",
    means: "NationalId",
    meansId: "848499494",
    state: " State",
    status: false,
    photo: "two.jpg",
  },
  {
    gsm: Math.random() * 100,
    lid: nanoid(),

    amount: 27000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "RADAR",
    codeAlt: "25",
    courseName: "APPA/RADAR OPERATION",
    dob: "2000-04-12",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),

    fullName: "Tombra Tari Franklyn",
    marital: "single",
    means: "NationalId",
    meansId: "848499494",
    state: " State",
    status: false,
    photo: "two.jpg",
  },
  {
    gsm: Math.random() * 100,
    lid: nanoid(),

    amount: 150000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "OTF",
    codeAlt: "5",
    courseName: "BASIC OIL, CHEMICAL AND LIQUEFIED GAS TANKER CARGO OPERATIONS",
    dob: "2000-04-12",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),

    fullName: "Tamaraebi Daniel Samuelson",
    marital: "single",
    means: "NationalId",
    meansId: "848499494",
    state: " State",
    status: false,
    photo: "two.jpg",
  },
  {
    gsm: Math.random() * 100,
    lid: nanoid(),

    amount: 83000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "GMDSS",
    codeAlt: "15",
    courseName: "GMDSS RADIO OPERATORS",
    dob: "2000-04-12",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),

    fullName: "Rukeme James Joshua",
    marital: "single",
    means: "NationalId",
    meansId: "848499494",
    state: " State",
    status: false,
    photo: "two.jpg",
  },
  {
    gsm: Math.random() * 100,
    lid: nanoid(),

    amount: 50000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "MOTM",
    codeAlt: "7",
    courseName: "MOTORMAN",
    dob: "2000-04-12",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),

    fullName: "Marshall Layefa Matthew",
    marital: "single",
    means: "NationalId",
    meansId: "848499494",
    state: " State",
    status: false,
    photo: "two.jpg",
  },
  {
    gsm: Math.random() * 100,
    lid: nanoid(),

    amount: 69000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "ADFF",
    codeAlt: "8",
    courseName: "Advanced Fire Fighting Certificate",
    dob: "2000-04-12",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),

    fullName: "Deimo Evans Kelvin",
    marital: "single",
    means: "NationalId",
    meansId: "848499494",
    state: " State",
    status: false,
    photo: "two.jpg",
  },
  {
    gsm: Math.random() * 100,
    lid: nanoid(),

    amount: 25500,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "PSCR",
    codeAlt: "15",
    courseName:
      "PROFICIENCY IN SURVIVAL CRAFT & RESCUE BOATS (OTHER THAN FAST RESCUE BOATS)",
    dob: "2000-04-12",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),

    fullName: "Francis Odili Precious",
    marital: "single",
    means: "NationalId",
    meansId: "848499494",
    state: " State",
    status: false,
    photo: "two.jpg",
  },
  {
    gsm: Math.random() * 100,
    lid: nanoid(),

    amount: 67000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "RADAR",
    codeAlt: "25",
    courseName: "APPA/RADAR OPERATION",
    dob: "2000-04-12",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),

    fullName: "Samuel Gift David",
    marital: "single",
    means: "NationalId",
    meansId: "848499494",
    state: " State",
    status: false,
    photo: "two.jpg",
  },
  {
    gsm: Math.random() * 100,
    lid: nanoid(),

    amount: 93000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "OTF",
    codeAlt: "5",
    courseName: "BASIC OIL, CHEMICAL AND LIQUEFIED GAS TANKER CARGO OPERATIONS",
    dob: "2000-04-12",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),

    fullName: "Victory Samuel Misson",
    marital: "single",
    means: "NationalId",
    meansId: "848499494",
    state: " State",
    status: false,
    photo: "two.jpg",
  },
  {
    gsm: Math.random() * 100,
    lid: nanoid(),

    amount: 45000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "GMDSS",
    codeAlt: "15",
    courseName: "GMDSS RADIO OPERATORS",
    dob: "2000-04-12",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),

    fullName: "Golden Praise Kurokeme",
    marital: "single",
    means: "NationalId",
    meansId: "848499494",
    state: " State",
    status: false,
    photo: "two.jpg",
  },
  {
    gsm: Math.random() * 100,
    lid: nanoid(),

    amount: 65000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "MOTM",
    codeAlt: "7",
    courseName: "MOTORMAN",
    dob: "2000-04-12",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),

    fullName: "Lucky Spencer Raymond",
    marital: "single",
    means: "NationalId",
    meansId: "848499494",
    state: " State",
    status: false,
    photo: "two.jpg",
  },
  {
    gsm: Math.random() * 100,
    lid: nanoid(),

    amount: 33000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "ADFF",
    codeAlt: "8",
    courseName: "Advanced Fire Fighting Certificate",
    dob: "2000-04-12",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),

    fullName: "Akpoebi Karike Boma",
    marital: "single",
    means: "NationalId",
    meansId: "848499494",
    state: " State",
    status: false,
    photo: "two.jpg",
  },
  {
    gsm: Math.random() * 100,
    lid: nanoid(),

    amount: 79000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "PSCR",
    codeAlt: "15",
    courseName:
      "PROFICIENCY IN SURVIVAL CRAFT & RESCUE BOATS (OTHER THAN FAST RESCUE BOATS)",
    dob: "2000-04-12",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),

    fullName: "Anthony komi Felix",
    marital: "single",
    means: "NationalId",
    meansId: "848499494",
    state: " State",
    status: false,
    photo: "two.jpg",
  },
];

const fakeData = fake.map((ele, i) => {
  const [first, second, third] = ele.fullName.split(" ");

  return {
    ...ele,
    gender: `${i % 2 === 0 ? "Male" : "Female"}`,
    firstName: first,
    middleName: second,
    lastName: third,
    startDate:'2024-06-12',
    endDate:"2024-05-10",
    printStatus:false
  };
});

export { fakeData, months,family };
