import { format } from "date-fns";
import { nanoid } from "nanoid";

const months = [
  { value: "", label: "All Months" },
  { value: "1", label: "January" },
  { value: "2", label: "February" },
  { value: "3", label: "March" },
  { value: "4", label: "April" },
  { value: "5", label: "May" },
  { value: "6", label: "June" },
  { value: "7", label: "July" },
  { value: "8", label: "August" },
  { value: "9", label: "September" },
  { value: "10", label: "October" },
  { value: "11", label: "November" },
  { value: "12", label: "December" },
];

const fake = [
  {
    lid: nanoid(),
    amount: 55000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "STCW",
    codeAlt: "1-4",
    courseName: "STCW BASIC SAFETY TRAINING",
    dob: "2000-04-12",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),
    fullName: "Evans Diegbe Diegbe",
    marital: "Single",
    means: "NationalId",
    meansId: "848499494",
    state: "Delta State",
    status: false,
    photo: "two.jpg",
  },
  {
    lid: nanoid(),

    amount: 70000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "ISPS",
    codeAlt: "11",
    courseName:
      "INTERNATIONAL SHIP & PORT FACILITIES (ISPS) SECURITY AWARENESS",
    dob: "2000-04-12",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),
    isRenewal: true,
    fullName: "Wex Daniel Adenikinju",
    marital: "Married",
    means: "NationalId",
    meansId: "848499494",
    state: "Ibadan State",
    status: false,
    photo: "two.jpg",
  },
  {
    lid: nanoid(),

    amount: 65000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "EDH",
    codeAlt: "6",
    courseName: "EFFICIENT DECK HAND",
    dob: "2000-04-12",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),

    fullName: "Junior John Doe",
    marital: "married",
    means: "NationalId",
    meansId: "848499494",
    state: "Lagos State",
    status: false,
    photo: "two.jpg",
  },
  {
    gsm: Math.random() * 100,
    lid: nanoid(),

    amount: 140000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "PSCR",
    codeAlt: "31",
    courseName:
      "PROFICIENCY IN SURVIVAL CRAFT, RESCUE BOATS AND FAST RESCUE BOATS",
    dob: "2000-04-12",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),

    fullName: "Chiboy Molt Run",
    marital: "single",
    means: "NationalId",
    meansId: "848499494",
    state: " State",
    status: false,
    photo: "two.jpg",
  },
  {
    gsm: Math.random() * 100,
    lid: nanoid(),

    amount: 65000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "MOTM",
    codeAlt: "7",
    courseName: "MOTORMAN",
    dob: "2000-04-12",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),

    fullName: "cha cha cha",
    marital: "single",
    means: "NationalId",
    meansId: "848499494",
    state: " State",
    status: false,
    photo: "two.jpg",
  },
  {
    gsm: Math.random() * 100,
    lid: nanoid(),

    amount: 140000,
    address: "lorem nigga",
    bank: "AMJU bank",
    country: "Nigeria",
    courseCode: "RADAR",
    codeAlt: "25",
    courseName: "APPA/RADAR OPERATION",
    dob: "2000-04-12",
    email: "youremail@lover.com",
    enrollDate: format(new Date(), "dd MMMM yy, hh:mm aaa"),

    fullName: "Doubra toniprr Vic",
    marital: "single",
    means: "NationalId",
    meansId: "848499494",
    state: " State",
    status: false,
    photo: "two.jpg",
  },
];

const fakeData = fake.map((ele, i) => ({
  ...ele,
  gender: `${i % 2 === 0 ? "Male" : "Female"}`,
}));

export {  fakeData,months };
